name: Backend CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Verify API_KEY exists
        run: |
          if [ -z "$API_KEY" ]; then
            echo "API_KEY is missing"
            exit 1
          else
            echo "API_KEY is set"
          fi

      - name: Run tests
        run: npm test
